"""Add adr_reports table

Revision ID: 5823c755a0d7
Revises: dbd8b22a4295
Create Date: 2026-06-24 16:19:52.262263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5823c755a0d7'
down_revision: Union[str, Sequence[str], None] = 'dbd8b22a4295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adr_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drug_name', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('naranjo_score', sa.Integer(), nullable=False),
    sa.Column('dpdp_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reported_by_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adr_reports_thread_id'), 'adr_reports', ['thread_id'], unique=False)
    op.drop_column('naranjo_results', 'adr_api_response')
    op.drop_column('naranjo_results', 'pvpi_payload')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('naranjo_results', sa.Column('pvpi_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('naranjo_results', sa.Column('adr_api_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    pass
    op.drop_index(op.f('ix_adr_reports_thread_id'), table_name='adr_reports')
    op.drop_table('adr_reports')
    # ### end Alembic commands ###
