"""Add NaranjoResult table

Revision ID: 5fee6455d59a
Revises: fa7523f53a48
Create Date: 2026-06-14 23:25:40.923225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fee6455d59a'
down_revision: Union[str, Sequence[str], None] = 'fa7523f53a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naranjo_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pharmacist_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('naranjo_score', sa.Integer(), nullable=False),
    sa.Column('naranjo_causality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adr_api_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pvpi_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacist_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_naranjo_results_patient_id'), 'naranjo_results', ['patient_id'], unique=False)
    op.create_index(op.f('ix_naranjo_results_pharmacist_id'), 'naranjo_results', ['pharmacist_id'], unique=False)
    op.create_index(op.f('ix_naranjo_results_thread_id'), 'naranjo_results', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_naranjo_results_thread_id'), table_name='naranjo_results')
    op.drop_index(op.f('ix_naranjo_results_pharmacist_id'), table_name='naranjo_results')
    op.drop_index(op.f('ix_naranjo_results_patient_id'), table_name='naranjo_results')
    op.drop_table('naranjo_results')
    # ### end Alembic commands ###
