"""Add pharmacist_thread_id to user table

Revision ID: af2053e2dd1e
Revises: 8be3233d8a5e
Create Date: 2026-06-14 23:05:20.846105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af2053e2dd1e'
down_revision: Union[str, Sequence[str], None] = '8be3233d8a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pharmacist_thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pharmacist_thread_id')
    # ### end Alembic commands ###
