"""Add PharmacistThread table

Revision ID: fa7523f53a48
Revises: af2053e2dd1e
Create Date: 2026-06-14 23:10:47.776142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa7523f53a48'
down_revision: Union[str, Sequence[str], None] = 'af2053e2dd1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacist_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacist_threads_thread_id'), 'pharmacist_threads', ['thread_id'], unique=True)
    op.create_index(op.f('ix_pharmacist_threads_user_id'), 'pharmacist_threads', ['user_id'], unique=False)
    op.drop_column('users', 'pharmacist_thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pharmacist_thread_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pharmacist_threads_user_id'), table_name='pharmacist_threads')
    op.drop_index(op.f('ix_pharmacist_threads_thread_id'), table_name='pharmacist_threads')
    op.drop_table('pharmacist_threads')
    # ### end Alembic commands ###
